services:
  web:
    build:
      context: .
    command: uvicorn handbook.asgi:application --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - ./handbook:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
    command: celery -A handbook worker -l info
    env_file:
      - .env
    volumes:
      - ./handbook:/app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
