# Generated by Django 6.0.4 on 2026-05-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
