# Generated by Django 6.0.4 on 2026-05-10 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_course_teachers(apps, schema_editor):
    CourseTeacher = apps.get_model("education", "CourseTeacher")
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        cursor.execute("SELECT course_id, user_id FROM education_course_teachers")
        rows = cursor.fetchall()

    CourseTeacher.objects.bulk_create(
        [
            CourseTeacher(course_id=course_id, teacher_id=user_id)
            for course_id, user_id in rows
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_submission_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teachers', to='education.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(copy_course_teachers, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RemoveField(
                    model_name='course',
                    name='teachers',
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='course',
                    name='teachers',
                    field=models.ManyToManyField(related_name='teaching_courses', through='education.CourseTeacher', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='courseteacher',
            constraint=models.UniqueConstraint(fields=('course', 'teacher'), name='unique_course_teacher'),
        ),
    ]
