# Generated by Django 6.0.4 on 2026-05-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_lesson_description_contentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('code', 'Code'), ('note', 'Note'), ('image', 'Image')], max_length=20),
        ),
    ]
