# Generated by Django 6.0.4 on 2026-05-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_contentblock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='solution_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='starter_code',
            field=models.TextField(blank=True),
        ),
    ]
