# Generated by Django 6.0.4 on 2026-05-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='solution_code',
        ),
    ]
