# Generated by Django 6.0.4 on 2026-05-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_remove_task_solution_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершено')], default='in_progress', max_length=20),
        ),
    ]
