# Generated by Django 6.0.4 on 2026-05-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_userprogress_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentBlock',
            new_name='LessonContentBlock',
        ),
    ]
