# Generated by Django 6.0.4 on 2026-05-19 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_remove_task_description_task_execution_time_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcontentblock',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('code', 'Code'), ('image', 'Image'), ('hint', 'Hint')], max_length=20),
        ),
        migrations.CreateModel(
            name='TaskHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='education.task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='taskcontentblock',
            name='hint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_blocks', to='education.taskhint'),
        ),
        migrations.CreateModel(
            name='TaskHintContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('code', 'Code'), ('image', 'Image'), ('note', 'Note')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='education.taskhint')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='taskhint',
            constraint=models.UniqueConstraint(fields=('task', 'order'), name='unique_hint_order_per_task'),
        ),
    ]
