# Generated by Django 6.0.4 on 2026-06-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
