# Generated by Django 6.0.4 on 2026-06-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_alter_test_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='input_data',
            field=models.TextField(blank=True),
        ),
    ]
